/**
 * @prooflens/epistemics
 *
 * The epistemic kernel of ProofLens.
 *
 * ProofLens exists to keep a hard line between what a proof assistant has
 * verified and what software (or a language model) believes that proof means.
 * That line is not a UI decoration: it is a data type, and it is enforced here.
 *
 * Two properties are guaranteed by construction:
 *
 *  1. **`verified` cannot be manufactured.** The only function that produces a
 *     `verified` claim is {@link transcribe}, and it demands a
 *     {@link KernelWitness} — a token that only the Formal IR loader can mint,
 *     and only for a declaration the Lean kernel actually accepted.
 *
 *  2. **Confidence never increases downstream.** Every derivation combines its
 *     inputs with {@link weakest}, so a chain of transformations can only move
 *     toward less certainty, never back toward more.
 *
 * @packageDocumentation
 */

/**
 * The epistemic states ProofLens distinguishes, ordered from strongest to
 * weakest. The order is meaningful: it is the lattice used by {@link weakest}.
 *
 * - `verified`     — asserted by the proof assistant's kernel.
 * - `derived`      — computed from verified data by a deterministic, inspectable rule.
 * - `interpreted`  — mapped onto mathematical meaning by a documented rule, or
 *                    declared by a human author via a semantic annotation.
 * - `heuristic`    — a rule-based guess that is expected to be wrong sometimes.
 * - `illustrative` — chosen for display; carries no mathematical claim at all.
 * - `speculative`  — produced by a language model or other unverified source.
 */
export const EPISTEMIC_ORDER = [
  "verified",
  "derived",
  "interpreted",
  "heuristic",
  "illustrative",
  "speculative",
] as const;

export type EpistemicStatus = (typeof EPISTEMIC_ORDER)[number];

/** Position in the lattice. Lower is stronger. */
export function rank(status: EpistemicStatus): number {
  return EPISTEMIC_ORDER.indexOf(status);
}

/**
 * The weakest (least certain) of the given statuses.
 *
 * This is the only combinator ProofLens uses to propagate epistemic state, and
 * it is why confidence can never be laundered upward through the pipeline.
 */
export function weakest(...statuses: EpistemicStatus[]): EpistemicStatus {
  if (statuses.length === 0) return "speculative";
  return statuses.reduce((a, b) => (rank(a) >= rank(b) ? a : b));
}

/** Is `status` at least as strong as `floor`? */
export function isAtLeast(status: EpistemicStatus, floor: EpistemicStatus): boolean {
  return rank(status) <= rank(floor);
}

/** Human-facing gloss, used by explanation and provenance surfaces. */
export const EPISTEMIC_GLOSS: Record<EpistemicStatus, string> = {
  verified: "Checked by the Lean kernel.",
  derived: "Computed from the verified statement by a deterministic rule.",
  interpreted: "A reading of the formal statement, not part of what was proved.",
  heuristic: "A rule-of-thumb guess that may be wrong.",
  illustrative: "A display choice. It makes no mathematical claim.",
  speculative: "Generated by a model. Not verified by anything.",
};

// ---------------------------------------------------------------------------
// Provenance
// ---------------------------------------------------------------------------

/** A span in a source file, 1-indexed lines, 0-indexed columns (Lean's convention). */
export interface SourceSpan {
  startLine: number;
  startColumn: number;
  endLine: number;
  endColumn: number;
}

/**
 * A pointer back into the formal mathematics.
 *
 * `path` is a structural path into the declaration's expression trees, e.g.
 * `conclusion.args[3]`. It is what lets the UI answer "why are you showing me
 * this?" by highlighting the exact subterm responsible.
 */
export interface SourceReference {
  system: string;
  declaration: string;
  module?: string | null;
  span?: SourceSpan | null;
  path?: string;
}

/**
 * A named, stable transformation rule.
 *
 * Every rule ID is part of ProofLens's public surface: it appears in provenance
 * output, it is referenced by tests, and it must not be renamed casually.
 */
export interface Rule {
  /** Stable identifier, e.g. `REL_UPPER_BOUND_001`. */
  id: string;
  /** One sentence, phrased as what the rule concluded. */
  description: string;
  /**
   * The strongest status this rule is ever allowed to produce.
   *
   * `verified` is excluded by the type: a rule is a computation, and no
   * computation earns kernel standing. Only {@link transcribe} produces
   * `verified`, and only against a {@link KernelWitness}.
   */
  produces: Exclude<EpistemicStatus, "verified">;
}

export interface Provenance {
  sources: SourceReference[];
  rule?: Rule;
  /** Free-form ids of upstream claims this one was computed from. */
  inputs?: string[];
  note?: string;
}

/** A value together with how much we are entitled to believe it. */
export interface Claim<T> {
  readonly value: T;
  readonly status: EpistemicStatus;
  readonly provenance: Provenance;
}

// ---------------------------------------------------------------------------
// Construction
// ---------------------------------------------------------------------------

/**
 * Module-local symbol. Deliberately NOT `Symbol.for`: a registry symbol is
 * reachable by any code in the realm that knows the string, which would make
 * the brand a naming convention rather than a capability. Because this symbol
 * is unreachable from outside this module, `mintKernelWitness` is the only way
 * to obtain a value that `transcribe` will accept.
 */
const WITNESS_BRAND: unique symbol = Symbol("prooflens.kernel-witness");

/**
 * Evidence that a declaration was accepted by a proof assistant's kernel.
 *
 * Minted only by `@prooflens/formal-ir`, and only for declarations whose
 * extraction reported no `sorry`. Holding one of these is what entitles a
 * caller to produce `verified` claims about that declaration.
 */
export interface KernelWitness {
  readonly [WITNESS_BRAND]: true;
  readonly system: string;
  readonly declaration: string;
  readonly module: string | null;
  /** Axioms the declaration's proof ultimately rests on. */
  readonly axioms: readonly string[];
}

/**
 * Mint a kernel witness.
 *
 * @internal Intended for `@prooflens/formal-ir` only. It is deliberately not
 * re-exported by any downstream package, and `test/no-forged-verification.test.ts`
 * asserts that no other package calls it.
 */
export function mintKernelWitness(args: {
  system: string;
  declaration: string;
  module: string | null;
  axioms: readonly string[];
  provedWithoutSorry: boolean;
}): KernelWitness | null {
  if (!args.provedWithoutSorry) return null;
  return {
    [WITNESS_BRAND]: true,
    system: args.system,
    declaration: args.declaration,
    module: args.module,
    axioms: args.axioms,
  };
}

/**
 * Record something the kernel actually asserted.
 *
 * This is the **only** producer of `verified` in the entire system.
 */
export function transcribe<T>(
  witness: KernelWitness,
  value: T,
  provenance: Omit<Provenance, "rule"> & { rule?: never },
): Claim<T> {
  if (
    witness === null ||
    typeof witness !== "object" ||
    !Object.hasOwn(witness, WITNESS_BRAND) ||
    (witness as { [WITNESS_BRAND]?: unknown })[WITNESS_BRAND] !== true
  ) {
    throw new TypeError(
      "transcribe() requires a KernelWitness minted by @prooflens/formal-ir. " +
        "Verified status cannot be constructed from arbitrary data.",
    );
  }
  return Object.freeze({
    value,
    status: "verified" as const,
    provenance: { ...provenance, rule: undefined },
  });
}

/**
 * Apply a rule to some inputs.
 *
 * The result's status is the weakest of the rule's ceiling and every input's
 * status. There is no way to pass a stronger status in.
 *
 * `"derived"` is included in the fold as a hard floor. The type of
 * `Rule.produces` already excludes `verified`, but types are erased at runtime
 * and this module's whole job is to be true of the running program, not only of
 * the one that typechecked. A rule is a computation; no computation earns
 * kernel standing, whatever a cast claims.
 */
export function derive<T>(
  value: T,
  rule: Rule,
  inputs: readonly Claim<unknown>[],
  provenance: Omit<Provenance, "rule">,
): Claim<T> {
  const status = weakest(rule.produces, "derived", ...inputs.map((c) => c.status));
  return Object.freeze({ value, status, provenance: { ...provenance, rule } });
}

/**
 * Record a claim whose status is asserted directly, for sources that are not
 * derivations — human semantic annotations, display choices, model output.
 *
 * `verified` is rejected: use {@link transcribe}.
 */
export function assert_<T>(
  value: T,
  status: Exclude<EpistemicStatus, "verified">,
  provenance: Provenance,
): Claim<T> {
  return Object.freeze({ value, status, provenance });
}

export { assert_ as state };

/** Map a claim's payload without touching its epistemic standing. */
export function mapClaim<A, B>(claim: Claim<A>, f: (a: A) => B): Claim<B> {
  return Object.freeze({
    value: f(claim.value),
    status: claim.status,
    provenance: claim.provenance,
  });
}

/**
 * Explicitly weaken a claim, recording why.
 *
 * Used when a downstream stage knows something the producer did not — for
 * example, that a bound was rendered on axes chosen for legibility rather than
 * mathematical necessity.
 */
export function weaken<T>(claim: Claim<T>, to: EpistemicStatus, note: string): Claim<T> {
  const status = weakest(claim.status, to);
  return Object.freeze({
    value: claim.value,
    status,
    provenance: { ...claim.provenance, note },
  });
}

/** Axioms that mathlib and Lean core consider unremarkable. */
export const STANDARD_AXIOMS: readonly string[] = ["propext", "Classical.choice", "Quot.sound"];

/** Axioms beyond the standard three — these are worth telling a human about. */
export function unusualAxioms(axioms: readonly string[]): string[] {
  return axioms.filter((a) => !STANDARD_AXIOMS.includes(a));
}
