#!/usr/bin/env node
/**
 * Bundle the ProofLens infoview widget.
 *
 * The Lean infoview supplies React through an import map, so `react` and
 * `react-dom` must stay external — bundling a second copy would give us a
 * different React instance than the host, and hooks would break.
 *
 * Output is deliberately unminified: it is committed to the repository so that
 * `lake build` works without a Node toolchain, and a readable diff is worth
 * more than a few kilobytes.
 */
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const result = await build({
  entryPoints: [resolve(root, "lean/widget/src/index.tsx")],
  outfile: resolve(root, "lean/ProofLens/Widget/prooflens.js"),
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: false,
  sourcemap: false,
  jsx: "transform",
  jsxFactory: "React.createElement",
  jsxFragment: "React.Fragment",
  external: ["react", "react-dom", "react/jsx-runtime", "@leanprover/infoview"],
  logLevel: "info",
  metafile: true,
  banner: {
    js: "// Generated by `pnpm build:widget`. Do not edit by hand — edit lean/widget/src instead.",
  },
});

const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
console.log(`ProofLens widget bundled: ${(bytes / 1024).toFixed(1)} kB`);
